eduardo_chami/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('menuApp.urls'), name='menuApp'),
    path('optionApp/', include('optionApp.urls'), name='optionApp')
]

menuApp/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'menuApp'

urlpatterns = [
    path('', MenuView.as_view(), name='home')
]

optionApp/urls.py
from django.contrib import admin
from django.urls import path
from .views import *

app_name = 'optionApp'

urlpatterns = [
    path('tabla', TablaView.as_view(), name='tabla'),
    path('loteria', LoteriaView.as_view(), name='loteria')
]

menuApp/models.py
from django.db import models

# Create your models here.

optionApp/models.py
from django.db import models

# Create your models here.


class Pais(models.Model):
    id = models.IntegerField(primary_key=True)
    nombre = models.CharField(max_length=50)
    continente = models.CharField(max_length=50)
    imagen = models.CharField(max_length=250)

menuApp/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse

# Create your views here.

class MenuView(View):
    def get(self, request, *args, **kwargs):
        context = {}
        html_content = render(request, 'menuApp/menu-view.html', context)
        return HttpResponse(html_content)

optionApp/views.py
from django.shortcuts import render
from django.views import View
from django.http import HttpResponse
import random

from .models import Pais

class TablaView(View):
    def get(self, request, *args, **kwargs):
        paises = Pais.objects.all()
        context = {"paises": paises}
        html_content = render(request, "optionApp/tabla-view.html", context)
        return HttpResponse(html_content)


class LoteriaView(View):
    def get(self, request, *args, **kwargs):
        randomList = [random.randint(1, 100) for _ in range(10)]
        context = {"numerosLoteria": sorted(randomList)}
        html_content = render(request, "optionApp/loteria-view.html", context)
        return HttpResponse(html_content)

templates/menuApp/menu-view.html
<h1>menu</h1>


<p>Seleccione una opcion</p>
<a href="{% url 'optionApp:loteria' %}"> Numeros de loteria </a>
<br/ >
<a href="{% url 'optionApp:tabla' %}"> Mis paises </a>

templates/optionApp/loteria-view.html
<h1>Estos son los números de la suerte en este momento</h1>

<ul>
  {% for n in numerosLoteria %}
  <li>{{n}}</li>
  {% endfor %}
</ul>
<br />
<a href="{% url 'menuApp:home' %}"> Volver </a>

templates/optionApp/tabla-view.html
<h1>Mis Países Favoritos</h1>

<table style="border: 1px solid black">
  <tr>
    <th>País</th>
    <th>Continente</th>
    <th>Bandera</th>
  </tr>
  {% for pais in paises %}
  <tr>
    <td style="border: 1px solid black">{{pais.nombre}}</td>
    <td style="border: 1px solid black">{{pais.continente}}</td>
    <td style="border: 1px solid black">
      <img src="{{pais.imagen}}" width="200px" height="120px" />
    </td>
  </tr>
  {% endfor %}
</table>
<br />
<a href="{% url 'menuApp:home' %}"> Volver </a>